// Generated by jextract

package io.github.kinsleykajiva.opusfile;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     unsigned char *body_data;
 *     long body_storage;
 *     long body_fill;
 *     long body_returned;
 *     int *lacing_vals;
 *     ogg_int64_t *granule_vals;
 *     long lacing_storage;
 *     long lacing_fill;
 *     long lacing_packet;
 *     long lacing_returned;
 *     unsigned char header[282];
 *     int header_fill;
 *     int e_o_s;
 *     int b_o_s;
 *     long serialno;
 *     long pageno;
 *     ogg_int64_t packetno;
 *     ogg_int64_t granulepos;
 * }
 * }
 */
public class ogg_stream_state {

    ogg_stream_state() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        opusfile_h.C_POINTER.withName("body_data"),
        opusfile_h.C_LONG.withName("body_storage"),
        opusfile_h.C_LONG.withName("body_fill"),
        opusfile_h.C_LONG.withName("body_returned"),
        MemoryLayout.paddingLayout(4),
        opusfile_h.C_POINTER.withName("lacing_vals"),
        opusfile_h.C_POINTER.withName("granule_vals"),
        opusfile_h.C_LONG.withName("lacing_storage"),
        opusfile_h.C_LONG.withName("lacing_fill"),
        opusfile_h.C_LONG.withName("lacing_packet"),
        opusfile_h.C_LONG.withName("lacing_returned"),
        MemoryLayout.sequenceLayout(282, opusfile_h.C_CHAR).withName("header"),
        MemoryLayout.paddingLayout(2),
        opusfile_h.C_INT.withName("header_fill"),
        opusfile_h.C_INT.withName("e_o_s"),
        opusfile_h.C_INT.withName("b_o_s"),
        opusfile_h.C_LONG.withName("serialno"),
        opusfile_h.C_LONG.withName("pageno"),
        opusfile_h.C_LONG_LONG.withName("packetno"),
        opusfile_h.C_LONG_LONG.withName("granulepos")
    ).withName("$anon$52:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout body_data$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("body_data"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned char *body_data
     * }
     */
    public static final AddressLayout body_data$layout() {
        return body_data$LAYOUT;
    }

    private static final long body_data$OFFSET = $LAYOUT.byteOffset(groupElement("body_data"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned char *body_data
     * }
     */
    public static final long body_data$offset() {
        return body_data$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned char *body_data
     * }
     */
    public static MemorySegment body_data(MemorySegment struct) {
        return struct.get(body_data$LAYOUT, body_data$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned char *body_data
     * }
     */
    public static void body_data(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(body_data$LAYOUT, body_data$OFFSET, fieldValue);
    }

    private static final OfInt body_storage$LAYOUT = (OfInt)$LAYOUT.select(groupElement("body_storage"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * long body_storage
     * }
     */
    public static final OfInt body_storage$layout() {
        return body_storage$LAYOUT;
    }

    private static final long body_storage$OFFSET = $LAYOUT.byteOffset(groupElement("body_storage"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * long body_storage
     * }
     */
    public static final long body_storage$offset() {
        return body_storage$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * long body_storage
     * }
     */
    public static int body_storage(MemorySegment struct) {
        return struct.get(body_storage$LAYOUT, body_storage$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * long body_storage
     * }
     */
    public static void body_storage(MemorySegment struct, int fieldValue) {
        struct.set(body_storage$LAYOUT, body_storage$OFFSET, fieldValue);
    }

    private static final OfInt body_fill$LAYOUT = (OfInt)$LAYOUT.select(groupElement("body_fill"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * long body_fill
     * }
     */
    public static final OfInt body_fill$layout() {
        return body_fill$LAYOUT;
    }

    private static final long body_fill$OFFSET = $LAYOUT.byteOffset(groupElement("body_fill"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * long body_fill
     * }
     */
    public static final long body_fill$offset() {
        return body_fill$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * long body_fill
     * }
     */
    public static int body_fill(MemorySegment struct) {
        return struct.get(body_fill$LAYOUT, body_fill$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * long body_fill
     * }
     */
    public static void body_fill(MemorySegment struct, int fieldValue) {
        struct.set(body_fill$LAYOUT, body_fill$OFFSET, fieldValue);
    }

    private static final OfInt body_returned$LAYOUT = (OfInt)$LAYOUT.select(groupElement("body_returned"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * long body_returned
     * }
     */
    public static final OfInt body_returned$layout() {
        return body_returned$LAYOUT;
    }

    private static final long body_returned$OFFSET = $LAYOUT.byteOffset(groupElement("body_returned"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * long body_returned
     * }
     */
    public static final long body_returned$offset() {
        return body_returned$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * long body_returned
     * }
     */
    public static int body_returned(MemorySegment struct) {
        return struct.get(body_returned$LAYOUT, body_returned$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * long body_returned
     * }
     */
    public static void body_returned(MemorySegment struct, int fieldValue) {
        struct.set(body_returned$LAYOUT, body_returned$OFFSET, fieldValue);
    }

    private static final AddressLayout lacing_vals$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("lacing_vals"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int *lacing_vals
     * }
     */
    public static final AddressLayout lacing_vals$layout() {
        return lacing_vals$LAYOUT;
    }

    private static final long lacing_vals$OFFSET = $LAYOUT.byteOffset(groupElement("lacing_vals"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int *lacing_vals
     * }
     */
    public static final long lacing_vals$offset() {
        return lacing_vals$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int *lacing_vals
     * }
     */
    public static MemorySegment lacing_vals(MemorySegment struct) {
        return struct.get(lacing_vals$LAYOUT, lacing_vals$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int *lacing_vals
     * }
     */
    public static void lacing_vals(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(lacing_vals$LAYOUT, lacing_vals$OFFSET, fieldValue);
    }

    private static final AddressLayout granule_vals$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("granule_vals"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ogg_int64_t *granule_vals
     * }
     */
    public static final AddressLayout granule_vals$layout() {
        return granule_vals$LAYOUT;
    }

    private static final long granule_vals$OFFSET = $LAYOUT.byteOffset(groupElement("granule_vals"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ogg_int64_t *granule_vals
     * }
     */
    public static final long granule_vals$offset() {
        return granule_vals$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ogg_int64_t *granule_vals
     * }
     */
    public static MemorySegment granule_vals(MemorySegment struct) {
        return struct.get(granule_vals$LAYOUT, granule_vals$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ogg_int64_t *granule_vals
     * }
     */
    public static void granule_vals(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(granule_vals$LAYOUT, granule_vals$OFFSET, fieldValue);
    }

    private static final OfInt lacing_storage$LAYOUT = (OfInt)$LAYOUT.select(groupElement("lacing_storage"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * long lacing_storage
     * }
     */
    public static final OfInt lacing_storage$layout() {
        return lacing_storage$LAYOUT;
    }

    private static final long lacing_storage$OFFSET = $LAYOUT.byteOffset(groupElement("lacing_storage"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * long lacing_storage
     * }
     */
    public static final long lacing_storage$offset() {
        return lacing_storage$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * long lacing_storage
     * }
     */
    public static int lacing_storage(MemorySegment struct) {
        return struct.get(lacing_storage$LAYOUT, lacing_storage$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * long lacing_storage
     * }
     */
    public static void lacing_storage(MemorySegment struct, int fieldValue) {
        struct.set(lacing_storage$LAYOUT, lacing_storage$OFFSET, fieldValue);
    }

    private static final OfInt lacing_fill$LAYOUT = (OfInt)$LAYOUT.select(groupElement("lacing_fill"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * long lacing_fill
     * }
     */
    public static final OfInt lacing_fill$layout() {
        return lacing_fill$LAYOUT;
    }

    private static final long lacing_fill$OFFSET = $LAYOUT.byteOffset(groupElement("lacing_fill"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * long lacing_fill
     * }
     */
    public static final long lacing_fill$offset() {
        return lacing_fill$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * long lacing_fill
     * }
     */
    public static int lacing_fill(MemorySegment struct) {
        return struct.get(lacing_fill$LAYOUT, lacing_fill$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * long lacing_fill
     * }
     */
    public static void lacing_fill(MemorySegment struct, int fieldValue) {
        struct.set(lacing_fill$LAYOUT, lacing_fill$OFFSET, fieldValue);
    }

    private static final OfInt lacing_packet$LAYOUT = (OfInt)$LAYOUT.select(groupElement("lacing_packet"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * long lacing_packet
     * }
     */
    public static final OfInt lacing_packet$layout() {
        return lacing_packet$LAYOUT;
    }

    private static final long lacing_packet$OFFSET = $LAYOUT.byteOffset(groupElement("lacing_packet"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * long lacing_packet
     * }
     */
    public static final long lacing_packet$offset() {
        return lacing_packet$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * long lacing_packet
     * }
     */
    public static int lacing_packet(MemorySegment struct) {
        return struct.get(lacing_packet$LAYOUT, lacing_packet$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * long lacing_packet
     * }
     */
    public static void lacing_packet(MemorySegment struct, int fieldValue) {
        struct.set(lacing_packet$LAYOUT, lacing_packet$OFFSET, fieldValue);
    }

    private static final OfInt lacing_returned$LAYOUT = (OfInt)$LAYOUT.select(groupElement("lacing_returned"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * long lacing_returned
     * }
     */
    public static final OfInt lacing_returned$layout() {
        return lacing_returned$LAYOUT;
    }

    private static final long lacing_returned$OFFSET = $LAYOUT.byteOffset(groupElement("lacing_returned"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * long lacing_returned
     * }
     */
    public static final long lacing_returned$offset() {
        return lacing_returned$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * long lacing_returned
     * }
     */
    public static int lacing_returned(MemorySegment struct) {
        return struct.get(lacing_returned$LAYOUT, lacing_returned$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * long lacing_returned
     * }
     */
    public static void lacing_returned(MemorySegment struct, int fieldValue) {
        struct.set(lacing_returned$LAYOUT, lacing_returned$OFFSET, fieldValue);
    }

    private static final SequenceLayout header$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("header"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned char header[282]
     * }
     */
    public static final SequenceLayout header$layout() {
        return header$LAYOUT;
    }

    private static final long header$OFFSET = $LAYOUT.byteOffset(groupElement("header"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned char header[282]
     * }
     */
    public static final long header$offset() {
        return header$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned char header[282]
     * }
     */
    public static MemorySegment header(MemorySegment struct) {
        return struct.asSlice(header$OFFSET, header$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned char header[282]
     * }
     */
    public static void header(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, header$OFFSET, header$LAYOUT.byteSize());
    }

    private static long[] header$DIMS = { 282 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * unsigned char header[282]
     * }
     */
    public static long[] header$dimensions() {
        return header$DIMS;
    }
    private static final VarHandle header$ELEM_HANDLE = header$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * unsigned char header[282]
     * }
     */
    public static byte header(MemorySegment struct, long index0) {
        return (byte)header$ELEM_HANDLE.get(struct, header$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * unsigned char header[282]
     * }
     */
    public static void header(MemorySegment struct, long index0, byte fieldValue) {
        header$ELEM_HANDLE.set(struct, header$OFFSET, index0, fieldValue);
    }

    private static final OfInt header_fill$LAYOUT = (OfInt)$LAYOUT.select(groupElement("header_fill"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int header_fill
     * }
     */
    public static final OfInt header_fill$layout() {
        return header_fill$LAYOUT;
    }

    private static final long header_fill$OFFSET = $LAYOUT.byteOffset(groupElement("header_fill"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int header_fill
     * }
     */
    public static final long header_fill$offset() {
        return header_fill$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int header_fill
     * }
     */
    public static int header_fill(MemorySegment struct) {
        return struct.get(header_fill$LAYOUT, header_fill$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int header_fill
     * }
     */
    public static void header_fill(MemorySegment struct, int fieldValue) {
        struct.set(header_fill$LAYOUT, header_fill$OFFSET, fieldValue);
    }

    private static final OfInt e_o_s$LAYOUT = (OfInt)$LAYOUT.select(groupElement("e_o_s"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int e_o_s
     * }
     */
    public static final OfInt e_o_s$layout() {
        return e_o_s$LAYOUT;
    }

    private static final long e_o_s$OFFSET = $LAYOUT.byteOffset(groupElement("e_o_s"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int e_o_s
     * }
     */
    public static final long e_o_s$offset() {
        return e_o_s$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int e_o_s
     * }
     */
    public static int e_o_s(MemorySegment struct) {
        return struct.get(e_o_s$LAYOUT, e_o_s$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int e_o_s
     * }
     */
    public static void e_o_s(MemorySegment struct, int fieldValue) {
        struct.set(e_o_s$LAYOUT, e_o_s$OFFSET, fieldValue);
    }

    private static final OfInt b_o_s$LAYOUT = (OfInt)$LAYOUT.select(groupElement("b_o_s"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int b_o_s
     * }
     */
    public static final OfInt b_o_s$layout() {
        return b_o_s$LAYOUT;
    }

    private static final long b_o_s$OFFSET = $LAYOUT.byteOffset(groupElement("b_o_s"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int b_o_s
     * }
     */
    public static final long b_o_s$offset() {
        return b_o_s$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int b_o_s
     * }
     */
    public static int b_o_s(MemorySegment struct) {
        return struct.get(b_o_s$LAYOUT, b_o_s$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int b_o_s
     * }
     */
    public static void b_o_s(MemorySegment struct, int fieldValue) {
        struct.set(b_o_s$LAYOUT, b_o_s$OFFSET, fieldValue);
    }

    private static final OfInt serialno$LAYOUT = (OfInt)$LAYOUT.select(groupElement("serialno"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * long serialno
     * }
     */
    public static final OfInt serialno$layout() {
        return serialno$LAYOUT;
    }

    private static final long serialno$OFFSET = $LAYOUT.byteOffset(groupElement("serialno"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * long serialno
     * }
     */
    public static final long serialno$offset() {
        return serialno$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * long serialno
     * }
     */
    public static int serialno(MemorySegment struct) {
        return struct.get(serialno$LAYOUT, serialno$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * long serialno
     * }
     */
    public static void serialno(MemorySegment struct, int fieldValue) {
        struct.set(serialno$LAYOUT, serialno$OFFSET, fieldValue);
    }

    private static final OfInt pageno$LAYOUT = (OfInt)$LAYOUT.select(groupElement("pageno"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * long pageno
     * }
     */
    public static final OfInt pageno$layout() {
        return pageno$LAYOUT;
    }

    private static final long pageno$OFFSET = $LAYOUT.byteOffset(groupElement("pageno"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * long pageno
     * }
     */
    public static final long pageno$offset() {
        return pageno$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * long pageno
     * }
     */
    public static int pageno(MemorySegment struct) {
        return struct.get(pageno$LAYOUT, pageno$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * long pageno
     * }
     */
    public static void pageno(MemorySegment struct, int fieldValue) {
        struct.set(pageno$LAYOUT, pageno$OFFSET, fieldValue);
    }

    private static final OfLong packetno$LAYOUT = (OfLong)$LAYOUT.select(groupElement("packetno"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ogg_int64_t packetno
     * }
     */
    public static final OfLong packetno$layout() {
        return packetno$LAYOUT;
    }

    private static final long packetno$OFFSET = $LAYOUT.byteOffset(groupElement("packetno"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ogg_int64_t packetno
     * }
     */
    public static final long packetno$offset() {
        return packetno$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ogg_int64_t packetno
     * }
     */
    public static long packetno(MemorySegment struct) {
        return struct.get(packetno$LAYOUT, packetno$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ogg_int64_t packetno
     * }
     */
    public static void packetno(MemorySegment struct, long fieldValue) {
        struct.set(packetno$LAYOUT, packetno$OFFSET, fieldValue);
    }

    private static final OfLong granulepos$LAYOUT = (OfLong)$LAYOUT.select(groupElement("granulepos"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ogg_int64_t granulepos
     * }
     */
    public static final OfLong granulepos$layout() {
        return granulepos$LAYOUT;
    }

    private static final long granulepos$OFFSET = $LAYOUT.byteOffset(groupElement("granulepos"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ogg_int64_t granulepos
     * }
     */
    public static final long granulepos$offset() {
        return granulepos$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ogg_int64_t granulepos
     * }
     */
    public static long granulepos(MemorySegment struct) {
        return struct.get(granulepos$LAYOUT, granulepos$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ogg_int64_t granulepos
     * }
     */
    public static void granulepos(MemorySegment struct, long fieldValue) {
        struct.set(granulepos$LAYOUT, granulepos$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

