// Generated by jextract

package io.github.kinsleykajiva.opusfile;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     unsigned char *packet;
 *     long bytes;
 *     long b_o_s;
 *     long e_o_s;
 *     ogg_int64_t granulepos;
 *     ogg_int64_t packetno;
 * }
 * }
 */
public class ogg_packet {

    ogg_packet() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        opusfile_h.C_POINTER.withName("packet"),
        opusfile_h.C_LONG.withName("bytes"),
        opusfile_h.C_LONG.withName("b_o_s"),
        opusfile_h.C_LONG.withName("e_o_s"),
        MemoryLayout.paddingLayout(4),
        opusfile_h.C_LONG_LONG.withName("granulepos"),
        opusfile_h.C_LONG_LONG.withName("packetno")
    ).withName("$anon$89:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout packet$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("packet"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned char *packet
     * }
     */
    public static final AddressLayout packet$layout() {
        return packet$LAYOUT;
    }

    private static final long packet$OFFSET = $LAYOUT.byteOffset(groupElement("packet"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned char *packet
     * }
     */
    public static final long packet$offset() {
        return packet$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned char *packet
     * }
     */
    public static MemorySegment packet(MemorySegment struct) {
        return struct.get(packet$LAYOUT, packet$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned char *packet
     * }
     */
    public static void packet(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(packet$LAYOUT, packet$OFFSET, fieldValue);
    }

    private static final OfInt bytes$LAYOUT = (OfInt)$LAYOUT.select(groupElement("bytes"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * long bytes
     * }
     */
    public static final OfInt bytes$layout() {
        return bytes$LAYOUT;
    }

    private static final long bytes$OFFSET = $LAYOUT.byteOffset(groupElement("bytes"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * long bytes
     * }
     */
    public static final long bytes$offset() {
        return bytes$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * long bytes
     * }
     */
    public static int bytes(MemorySegment struct) {
        return struct.get(bytes$LAYOUT, bytes$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * long bytes
     * }
     */
    public static void bytes(MemorySegment struct, int fieldValue) {
        struct.set(bytes$LAYOUT, bytes$OFFSET, fieldValue);
    }

    private static final OfInt b_o_s$LAYOUT = (OfInt)$LAYOUT.select(groupElement("b_o_s"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * long b_o_s
     * }
     */
    public static final OfInt b_o_s$layout() {
        return b_o_s$LAYOUT;
    }

    private static final long b_o_s$OFFSET = $LAYOUT.byteOffset(groupElement("b_o_s"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * long b_o_s
     * }
     */
    public static final long b_o_s$offset() {
        return b_o_s$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * long b_o_s
     * }
     */
    public static int b_o_s(MemorySegment struct) {
        return struct.get(b_o_s$LAYOUT, b_o_s$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * long b_o_s
     * }
     */
    public static void b_o_s(MemorySegment struct, int fieldValue) {
        struct.set(b_o_s$LAYOUT, b_o_s$OFFSET, fieldValue);
    }

    private static final OfInt e_o_s$LAYOUT = (OfInt)$LAYOUT.select(groupElement("e_o_s"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * long e_o_s
     * }
     */
    public static final OfInt e_o_s$layout() {
        return e_o_s$LAYOUT;
    }

    private static final long e_o_s$OFFSET = $LAYOUT.byteOffset(groupElement("e_o_s"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * long e_o_s
     * }
     */
    public static final long e_o_s$offset() {
        return e_o_s$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * long e_o_s
     * }
     */
    public static int e_o_s(MemorySegment struct) {
        return struct.get(e_o_s$LAYOUT, e_o_s$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * long e_o_s
     * }
     */
    public static void e_o_s(MemorySegment struct, int fieldValue) {
        struct.set(e_o_s$LAYOUT, e_o_s$OFFSET, fieldValue);
    }

    private static final OfLong granulepos$LAYOUT = (OfLong)$LAYOUT.select(groupElement("granulepos"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ogg_int64_t granulepos
     * }
     */
    public static final OfLong granulepos$layout() {
        return granulepos$LAYOUT;
    }

    private static final long granulepos$OFFSET = $LAYOUT.byteOffset(groupElement("granulepos"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ogg_int64_t granulepos
     * }
     */
    public static final long granulepos$offset() {
        return granulepos$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ogg_int64_t granulepos
     * }
     */
    public static long granulepos(MemorySegment struct) {
        return struct.get(granulepos$LAYOUT, granulepos$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ogg_int64_t granulepos
     * }
     */
    public static void granulepos(MemorySegment struct, long fieldValue) {
        struct.set(granulepos$LAYOUT, granulepos$OFFSET, fieldValue);
    }

    private static final OfLong packetno$LAYOUT = (OfLong)$LAYOUT.select(groupElement("packetno"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * ogg_int64_t packetno
     * }
     */
    public static final OfLong packetno$layout() {
        return packetno$LAYOUT;
    }

    private static final long packetno$OFFSET = $LAYOUT.byteOffset(groupElement("packetno"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * ogg_int64_t packetno
     * }
     */
    public static final long packetno$offset() {
        return packetno$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * ogg_int64_t packetno
     * }
     */
    public static long packetno(MemorySegment struct) {
        return struct.get(packetno$LAYOUT, packetno$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * ogg_int64_t packetno
     * }
     */
    public static void packetno(MemorySegment struct, long fieldValue) {
        struct.set(packetno$LAYOUT, packetno$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

