// Generated by jextract

package io.github.kinsleykajiva.opusfile;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef int (*op_decode_cb_func)(void *, OpusMSDecoder *, void *, const ogg_packet *, int, int, int, int)
 * }
 */
public final class op_decode_cb_func {

    private op_decode_cb_func() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        int apply(MemorySegment _ctx, MemorySegment _decoder, MemorySegment _pcm, MemorySegment _op, int _nsamples, int _nchannels, int _format, int _li);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
        opusfile_h.C_INT,
        opusfile_h.C_POINTER,
        opusfile_h.C_POINTER,
        opusfile_h.C_POINTER,
        opusfile_h.C_POINTER,
        opusfile_h.C_INT,
        opusfile_h.C_INT,
        opusfile_h.C_INT,
        opusfile_h.C_INT
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = opusfile_h.upcallHandle(op_decode_cb_func.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(op_decode_cb_func.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static int invoke(MemorySegment funcPtr, MemorySegment _ctx, MemorySegment _decoder, MemorySegment _pcm, MemorySegment _op, int _nsamples, int _nchannels, int _format, int _li) {
        try {
            return (int) DOWN$MH.invokeExact(funcPtr, _ctx, _decoder, _pcm, _op, _nsamples, _nchannels, _format, _li);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

