// Generated by jextract

package io.github.kinsleykajiva.opusfile;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct OpusServerInfo {
 *     char *name;
 *     char *description;
 *     char *genre;
 *     char *url;
 *     char *server;
 *     char *content_type;
 *     opus_int32 bitrate_kbps;
 *     int is_public;
 *     int is_ssl;
 * }
 * }
 */
public class OpusServerInfo {

    OpusServerInfo() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        opusfile_h.C_POINTER.withName("name"),
        opusfile_h.C_POINTER.withName("description"),
        opusfile_h.C_POINTER.withName("genre"),
        opusfile_h.C_POINTER.withName("url"),
        opusfile_h.C_POINTER.withName("server"),
        opusfile_h.C_POINTER.withName("content_type"),
        opusfile_h.C_INT.withName("bitrate_kbps"),
        opusfile_h.C_INT.withName("is_public"),
        opusfile_h.C_INT.withName("is_ssl"),
        MemoryLayout.paddingLayout(4)
    ).withName("OpusServerInfo");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout name$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("name"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char *name
     * }
     */
    public static final AddressLayout name$layout() {
        return name$LAYOUT;
    }

    private static final long name$OFFSET = $LAYOUT.byteOffset(groupElement("name"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char *name
     * }
     */
    public static final long name$offset() {
        return name$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char *name
     * }
     */
    public static MemorySegment name(MemorySegment struct) {
        return struct.get(name$LAYOUT, name$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char *name
     * }
     */
    public static void name(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(name$LAYOUT, name$OFFSET, fieldValue);
    }

    private static final AddressLayout description$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("description"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char *description
     * }
     */
    public static final AddressLayout description$layout() {
        return description$LAYOUT;
    }

    private static final long description$OFFSET = $LAYOUT.byteOffset(groupElement("description"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char *description
     * }
     */
    public static final long description$offset() {
        return description$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char *description
     * }
     */
    public static MemorySegment description(MemorySegment struct) {
        return struct.get(description$LAYOUT, description$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char *description
     * }
     */
    public static void description(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(description$LAYOUT, description$OFFSET, fieldValue);
    }

    private static final AddressLayout genre$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("genre"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char *genre
     * }
     */
    public static final AddressLayout genre$layout() {
        return genre$LAYOUT;
    }

    private static final long genre$OFFSET = $LAYOUT.byteOffset(groupElement("genre"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char *genre
     * }
     */
    public static final long genre$offset() {
        return genre$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char *genre
     * }
     */
    public static MemorySegment genre(MemorySegment struct) {
        return struct.get(genre$LAYOUT, genre$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char *genre
     * }
     */
    public static void genre(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(genre$LAYOUT, genre$OFFSET, fieldValue);
    }

    private static final AddressLayout url$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("url"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char *url
     * }
     */
    public static final AddressLayout url$layout() {
        return url$LAYOUT;
    }

    private static final long url$OFFSET = $LAYOUT.byteOffset(groupElement("url"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char *url
     * }
     */
    public static final long url$offset() {
        return url$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char *url
     * }
     */
    public static MemorySegment url(MemorySegment struct) {
        return struct.get(url$LAYOUT, url$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char *url
     * }
     */
    public static void url(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(url$LAYOUT, url$OFFSET, fieldValue);
    }

    private static final AddressLayout server$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("server"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char *server
     * }
     */
    public static final AddressLayout server$layout() {
        return server$LAYOUT;
    }

    private static final long server$OFFSET = $LAYOUT.byteOffset(groupElement("server"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char *server
     * }
     */
    public static final long server$offset() {
        return server$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char *server
     * }
     */
    public static MemorySegment server(MemorySegment struct) {
        return struct.get(server$LAYOUT, server$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char *server
     * }
     */
    public static void server(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(server$LAYOUT, server$OFFSET, fieldValue);
    }

    private static final AddressLayout content_type$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("content_type"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char *content_type
     * }
     */
    public static final AddressLayout content_type$layout() {
        return content_type$LAYOUT;
    }

    private static final long content_type$OFFSET = $LAYOUT.byteOffset(groupElement("content_type"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char *content_type
     * }
     */
    public static final long content_type$offset() {
        return content_type$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char *content_type
     * }
     */
    public static MemorySegment content_type(MemorySegment struct) {
        return struct.get(content_type$LAYOUT, content_type$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char *content_type
     * }
     */
    public static void content_type(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(content_type$LAYOUT, content_type$OFFSET, fieldValue);
    }

    private static final OfInt bitrate_kbps$LAYOUT = (OfInt)$LAYOUT.select(groupElement("bitrate_kbps"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * opus_int32 bitrate_kbps
     * }
     */
    public static final OfInt bitrate_kbps$layout() {
        return bitrate_kbps$LAYOUT;
    }

    private static final long bitrate_kbps$OFFSET = $LAYOUT.byteOffset(groupElement("bitrate_kbps"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * opus_int32 bitrate_kbps
     * }
     */
    public static final long bitrate_kbps$offset() {
        return bitrate_kbps$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * opus_int32 bitrate_kbps
     * }
     */
    public static int bitrate_kbps(MemorySegment struct) {
        return struct.get(bitrate_kbps$LAYOUT, bitrate_kbps$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * opus_int32 bitrate_kbps
     * }
     */
    public static void bitrate_kbps(MemorySegment struct, int fieldValue) {
        struct.set(bitrate_kbps$LAYOUT, bitrate_kbps$OFFSET, fieldValue);
    }

    private static final OfInt is_public$LAYOUT = (OfInt)$LAYOUT.select(groupElement("is_public"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int is_public
     * }
     */
    public static final OfInt is_public$layout() {
        return is_public$LAYOUT;
    }

    private static final long is_public$OFFSET = $LAYOUT.byteOffset(groupElement("is_public"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int is_public
     * }
     */
    public static final long is_public$offset() {
        return is_public$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int is_public
     * }
     */
    public static int is_public(MemorySegment struct) {
        return struct.get(is_public$LAYOUT, is_public$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int is_public
     * }
     */
    public static void is_public(MemorySegment struct, int fieldValue) {
        struct.set(is_public$LAYOUT, is_public$OFFSET, fieldValue);
    }

    private static final OfInt is_ssl$LAYOUT = (OfInt)$LAYOUT.select(groupElement("is_ssl"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int is_ssl
     * }
     */
    public static final OfInt is_ssl$layout() {
        return is_ssl$LAYOUT;
    }

    private static final long is_ssl$OFFSET = $LAYOUT.byteOffset(groupElement("is_ssl"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int is_ssl
     * }
     */
    public static final long is_ssl$offset() {
        return is_ssl$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int is_ssl
     * }
     */
    public static int is_ssl(MemorySegment struct) {
        return struct.get(is_ssl$LAYOUT, is_ssl$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int is_ssl
     * }
     */
    public static void is_ssl(MemorySegment struct, int fieldValue) {
        struct.set(is_ssl$LAYOUT, is_ssl$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

