// Generated by jextract

package io.github.kinsleykajiva.opusfile;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct OpusTags {
 *     char **user_comments;
 *     int *comment_lengths;
 *     int comments;
 *     char *vendor;
 * }
 * }
 */
public class OpusTags {

    OpusTags() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        opusfile_h.C_POINTER.withName("user_comments"),
        opusfile_h.C_POINTER.withName("comment_lengths"),
        opusfile_h.C_INT.withName("comments"),
        MemoryLayout.paddingLayout(4),
        opusfile_h.C_POINTER.withName("vendor")
    ).withName("OpusTags");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout user_comments$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("user_comments"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char **user_comments
     * }
     */
    public static final AddressLayout user_comments$layout() {
        return user_comments$LAYOUT;
    }

    private static final long user_comments$OFFSET = $LAYOUT.byteOffset(groupElement("user_comments"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char **user_comments
     * }
     */
    public static final long user_comments$offset() {
        return user_comments$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char **user_comments
     * }
     */
    public static MemorySegment user_comments(MemorySegment struct) {
        return struct.get(user_comments$LAYOUT, user_comments$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char **user_comments
     * }
     */
    public static void user_comments(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(user_comments$LAYOUT, user_comments$OFFSET, fieldValue);
    }

    private static final AddressLayout comment_lengths$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("comment_lengths"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int *comment_lengths
     * }
     */
    public static final AddressLayout comment_lengths$layout() {
        return comment_lengths$LAYOUT;
    }

    private static final long comment_lengths$OFFSET = $LAYOUT.byteOffset(groupElement("comment_lengths"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int *comment_lengths
     * }
     */
    public static final long comment_lengths$offset() {
        return comment_lengths$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int *comment_lengths
     * }
     */
    public static MemorySegment comment_lengths(MemorySegment struct) {
        return struct.get(comment_lengths$LAYOUT, comment_lengths$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int *comment_lengths
     * }
     */
    public static void comment_lengths(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(comment_lengths$LAYOUT, comment_lengths$OFFSET, fieldValue);
    }

    private static final OfInt comments$LAYOUT = (OfInt)$LAYOUT.select(groupElement("comments"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int comments
     * }
     */
    public static final OfInt comments$layout() {
        return comments$LAYOUT;
    }

    private static final long comments$OFFSET = $LAYOUT.byteOffset(groupElement("comments"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int comments
     * }
     */
    public static final long comments$offset() {
        return comments$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int comments
     * }
     */
    public static int comments(MemorySegment struct) {
        return struct.get(comments$LAYOUT, comments$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int comments
     * }
     */
    public static void comments(MemorySegment struct, int fieldValue) {
        struct.set(comments$LAYOUT, comments$OFFSET, fieldValue);
    }

    private static final AddressLayout vendor$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("vendor"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char *vendor
     * }
     */
    public static final AddressLayout vendor$layout() {
        return vendor$LAYOUT;
    }

    private static final long vendor$OFFSET = $LAYOUT.byteOffset(groupElement("vendor"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char *vendor
     * }
     */
    public static final long vendor$offset() {
        return vendor$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char *vendor
     * }
     */
    public static MemorySegment vendor(MemorySegment struct) {
        return struct.get(vendor$LAYOUT, vendor$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char *vendor
     * }
     */
    public static void vendor(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(vendor$LAYOUT, vendor$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

