// Generated by jextract

package io.github.kinsleykajiva.opusfile;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct OpusHead {
 *     int version;
 *     int channel_count;
 *     unsigned int pre_skip;
 *     opus_uint32 input_sample_rate;
 *     int output_gain;
 *     int mapping_family;
 *     int stream_count;
 *     int coupled_count;
 *     unsigned char mapping[255];
 * }
 * }
 */
public class OpusHead {

    OpusHead() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        opusfile_h.C_INT.withName("version"),
        opusfile_h.C_INT.withName("channel_count"),
        opusfile_h.C_INT.withName("pre_skip"),
        opusfile_h.C_INT.withName("input_sample_rate"),
        opusfile_h.C_INT.withName("output_gain"),
        opusfile_h.C_INT.withName("mapping_family"),
        opusfile_h.C_INT.withName("stream_count"),
        opusfile_h.C_INT.withName("coupled_count"),
        MemoryLayout.sequenceLayout(255, opusfile_h.C_CHAR).withName("mapping"),
        MemoryLayout.paddingLayout(1)
    ).withName("OpusHead");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt version$LAYOUT = (OfInt)$LAYOUT.select(groupElement("version"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int version
     * }
     */
    public static final OfInt version$layout() {
        return version$LAYOUT;
    }

    private static final long version$OFFSET = $LAYOUT.byteOffset(groupElement("version"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int version
     * }
     */
    public static final long version$offset() {
        return version$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int version
     * }
     */
    public static int version(MemorySegment struct) {
        return struct.get(version$LAYOUT, version$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int version
     * }
     */
    public static void version(MemorySegment struct, int fieldValue) {
        struct.set(version$LAYOUT, version$OFFSET, fieldValue);
    }

    private static final OfInt channel_count$LAYOUT = (OfInt)$LAYOUT.select(groupElement("channel_count"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int channel_count
     * }
     */
    public static final OfInt channel_count$layout() {
        return channel_count$LAYOUT;
    }

    private static final long channel_count$OFFSET = $LAYOUT.byteOffset(groupElement("channel_count"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int channel_count
     * }
     */
    public static final long channel_count$offset() {
        return channel_count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int channel_count
     * }
     */
    public static int channel_count(MemorySegment struct) {
        return struct.get(channel_count$LAYOUT, channel_count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int channel_count
     * }
     */
    public static void channel_count(MemorySegment struct, int fieldValue) {
        struct.set(channel_count$LAYOUT, channel_count$OFFSET, fieldValue);
    }

    private static final OfInt pre_skip$LAYOUT = (OfInt)$LAYOUT.select(groupElement("pre_skip"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned int pre_skip
     * }
     */
    public static final OfInt pre_skip$layout() {
        return pre_skip$LAYOUT;
    }

    private static final long pre_skip$OFFSET = $LAYOUT.byteOffset(groupElement("pre_skip"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned int pre_skip
     * }
     */
    public static final long pre_skip$offset() {
        return pre_skip$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned int pre_skip
     * }
     */
    public static int pre_skip(MemorySegment struct) {
        return struct.get(pre_skip$LAYOUT, pre_skip$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned int pre_skip
     * }
     */
    public static void pre_skip(MemorySegment struct, int fieldValue) {
        struct.set(pre_skip$LAYOUT, pre_skip$OFFSET, fieldValue);
    }

    private static final OfInt input_sample_rate$LAYOUT = (OfInt)$LAYOUT.select(groupElement("input_sample_rate"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * opus_uint32 input_sample_rate
     * }
     */
    public static final OfInt input_sample_rate$layout() {
        return input_sample_rate$LAYOUT;
    }

    private static final long input_sample_rate$OFFSET = $LAYOUT.byteOffset(groupElement("input_sample_rate"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * opus_uint32 input_sample_rate
     * }
     */
    public static final long input_sample_rate$offset() {
        return input_sample_rate$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * opus_uint32 input_sample_rate
     * }
     */
    public static int input_sample_rate(MemorySegment struct) {
        return struct.get(input_sample_rate$LAYOUT, input_sample_rate$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * opus_uint32 input_sample_rate
     * }
     */
    public static void input_sample_rate(MemorySegment struct, int fieldValue) {
        struct.set(input_sample_rate$LAYOUT, input_sample_rate$OFFSET, fieldValue);
    }

    private static final OfInt output_gain$LAYOUT = (OfInt)$LAYOUT.select(groupElement("output_gain"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int output_gain
     * }
     */
    public static final OfInt output_gain$layout() {
        return output_gain$LAYOUT;
    }

    private static final long output_gain$OFFSET = $LAYOUT.byteOffset(groupElement("output_gain"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int output_gain
     * }
     */
    public static final long output_gain$offset() {
        return output_gain$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int output_gain
     * }
     */
    public static int output_gain(MemorySegment struct) {
        return struct.get(output_gain$LAYOUT, output_gain$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int output_gain
     * }
     */
    public static void output_gain(MemorySegment struct, int fieldValue) {
        struct.set(output_gain$LAYOUT, output_gain$OFFSET, fieldValue);
    }

    private static final OfInt mapping_family$LAYOUT = (OfInt)$LAYOUT.select(groupElement("mapping_family"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int mapping_family
     * }
     */
    public static final OfInt mapping_family$layout() {
        return mapping_family$LAYOUT;
    }

    private static final long mapping_family$OFFSET = $LAYOUT.byteOffset(groupElement("mapping_family"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int mapping_family
     * }
     */
    public static final long mapping_family$offset() {
        return mapping_family$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int mapping_family
     * }
     */
    public static int mapping_family(MemorySegment struct) {
        return struct.get(mapping_family$LAYOUT, mapping_family$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int mapping_family
     * }
     */
    public static void mapping_family(MemorySegment struct, int fieldValue) {
        struct.set(mapping_family$LAYOUT, mapping_family$OFFSET, fieldValue);
    }

    private static final OfInt stream_count$LAYOUT = (OfInt)$LAYOUT.select(groupElement("stream_count"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int stream_count
     * }
     */
    public static final OfInt stream_count$layout() {
        return stream_count$LAYOUT;
    }

    private static final long stream_count$OFFSET = $LAYOUT.byteOffset(groupElement("stream_count"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int stream_count
     * }
     */
    public static final long stream_count$offset() {
        return stream_count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int stream_count
     * }
     */
    public static int stream_count(MemorySegment struct) {
        return struct.get(stream_count$LAYOUT, stream_count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int stream_count
     * }
     */
    public static void stream_count(MemorySegment struct, int fieldValue) {
        struct.set(stream_count$LAYOUT, stream_count$OFFSET, fieldValue);
    }

    private static final OfInt coupled_count$LAYOUT = (OfInt)$LAYOUT.select(groupElement("coupled_count"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int coupled_count
     * }
     */
    public static final OfInt coupled_count$layout() {
        return coupled_count$LAYOUT;
    }

    private static final long coupled_count$OFFSET = $LAYOUT.byteOffset(groupElement("coupled_count"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int coupled_count
     * }
     */
    public static final long coupled_count$offset() {
        return coupled_count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int coupled_count
     * }
     */
    public static int coupled_count(MemorySegment struct) {
        return struct.get(coupled_count$LAYOUT, coupled_count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int coupled_count
     * }
     */
    public static void coupled_count(MemorySegment struct, int fieldValue) {
        struct.set(coupled_count$LAYOUT, coupled_count$OFFSET, fieldValue);
    }

    private static final SequenceLayout mapping$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("mapping"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned char mapping[255]
     * }
     */
    public static final SequenceLayout mapping$layout() {
        return mapping$LAYOUT;
    }

    private static final long mapping$OFFSET = $LAYOUT.byteOffset(groupElement("mapping"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned char mapping[255]
     * }
     */
    public static final long mapping$offset() {
        return mapping$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned char mapping[255]
     * }
     */
    public static MemorySegment mapping(MemorySegment struct) {
        return struct.asSlice(mapping$OFFSET, mapping$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned char mapping[255]
     * }
     */
    public static void mapping(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, mapping$OFFSET, mapping$LAYOUT.byteSize());
    }

    private static long[] mapping$DIMS = { 255 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * unsigned char mapping[255]
     * }
     */
    public static long[] mapping$dimensions() {
        return mapping$DIMS;
    }
    private static final VarHandle mapping$ELEM_HANDLE = mapping$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * unsigned char mapping[255]
     * }
     */
    public static byte mapping(MemorySegment struct, long index0) {
        return (byte)mapping$ELEM_HANDLE.get(struct, mapping$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * unsigned char mapping[255]
     * }
     */
    public static void mapping(MemorySegment struct, long index0, byte fieldValue) {
        mapping$ELEM_HANDLE.set(struct, mapping$OFFSET, index0, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

