// Generated by jextract

package io.github.kinsleykajiva.opusenc;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef void (*ope_packet_func)(void *, const unsigned char *, opus_int32, opus_uint32)
 * }
 */
public final class ope_packet_func {

    private ope_packet_func() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        void apply(MemorySegment user_data, MemorySegment packet_ptr, int packet_len, int flags);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
        opusenc_h.C_POINTER,
        opusenc_h.C_POINTER,
        opusenc_h.C_INT,
        opusenc_h.C_INT
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = opusenc_h.upcallHandle(ope_packet_func.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(ope_packet_func.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static void invoke(MemorySegment funcPtr, MemorySegment user_data, MemorySegment packet_ptr, int packet_len, int flags) {
        try {
             DOWN$MH.invokeExact(funcPtr, user_data, packet_ptr, packet_len, flags);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

