// Generated by jextract

package io.github.kinsleykajiva.ogg;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     unsigned char *data;
 *     int storage;
 *     int fill;
 *     int returned;
 *     int unsynced;
 *     int headerbytes;
 *     int bodybytes;
 * }
 * }
 */
public class ogg_sync_state {

    ogg_sync_state() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        ogg_h.C_POINTER.withName("data"),
        ogg_h.C_INT.withName("storage"),
        ogg_h.C_INT.withName("fill"),
        ogg_h.C_INT.withName("returned"),
        ogg_h.C_INT.withName("unsynced"),
        ogg_h.C_INT.withName("headerbytes"),
        ogg_h.C_INT.withName("bodybytes")
    ).withName("$anon$104:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout data$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("data"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned char *data
     * }
     */
    public static final AddressLayout data$layout() {
        return data$LAYOUT;
    }

    private static final long data$OFFSET = $LAYOUT.byteOffset(groupElement("data"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned char *data
     * }
     */
    public static final long data$offset() {
        return data$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned char *data
     * }
     */
    public static MemorySegment data(MemorySegment struct) {
        return struct.get(data$LAYOUT, data$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned char *data
     * }
     */
    public static void data(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(data$LAYOUT, data$OFFSET, fieldValue);
    }

    private static final OfInt storage$LAYOUT = (OfInt)$LAYOUT.select(groupElement("storage"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int storage
     * }
     */
    public static final OfInt storage$layout() {
        return storage$LAYOUT;
    }

    private static final long storage$OFFSET = $LAYOUT.byteOffset(groupElement("storage"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int storage
     * }
     */
    public static final long storage$offset() {
        return storage$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int storage
     * }
     */
    public static int storage(MemorySegment struct) {
        return struct.get(storage$LAYOUT, storage$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int storage
     * }
     */
    public static void storage(MemorySegment struct, int fieldValue) {
        struct.set(storage$LAYOUT, storage$OFFSET, fieldValue);
    }

    private static final OfInt fill$LAYOUT = (OfInt)$LAYOUT.select(groupElement("fill"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int fill
     * }
     */
    public static final OfInt fill$layout() {
        return fill$LAYOUT;
    }

    private static final long fill$OFFSET = $LAYOUT.byteOffset(groupElement("fill"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int fill
     * }
     */
    public static final long fill$offset() {
        return fill$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int fill
     * }
     */
    public static int fill(MemorySegment struct) {
        return struct.get(fill$LAYOUT, fill$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int fill
     * }
     */
    public static void fill(MemorySegment struct, int fieldValue) {
        struct.set(fill$LAYOUT, fill$OFFSET, fieldValue);
    }

    private static final OfInt returned$LAYOUT = (OfInt)$LAYOUT.select(groupElement("returned"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int returned
     * }
     */
    public static final OfInt returned$layout() {
        return returned$LAYOUT;
    }

    private static final long returned$OFFSET = $LAYOUT.byteOffset(groupElement("returned"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int returned
     * }
     */
    public static final long returned$offset() {
        return returned$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int returned
     * }
     */
    public static int returned(MemorySegment struct) {
        return struct.get(returned$LAYOUT, returned$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int returned
     * }
     */
    public static void returned(MemorySegment struct, int fieldValue) {
        struct.set(returned$LAYOUT, returned$OFFSET, fieldValue);
    }

    private static final OfInt unsynced$LAYOUT = (OfInt)$LAYOUT.select(groupElement("unsynced"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int unsynced
     * }
     */
    public static final OfInt unsynced$layout() {
        return unsynced$LAYOUT;
    }

    private static final long unsynced$OFFSET = $LAYOUT.byteOffset(groupElement("unsynced"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int unsynced
     * }
     */
    public static final long unsynced$offset() {
        return unsynced$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int unsynced
     * }
     */
    public static int unsynced(MemorySegment struct) {
        return struct.get(unsynced$LAYOUT, unsynced$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int unsynced
     * }
     */
    public static void unsynced(MemorySegment struct, int fieldValue) {
        struct.set(unsynced$LAYOUT, unsynced$OFFSET, fieldValue);
    }

    private static final OfInt headerbytes$LAYOUT = (OfInt)$LAYOUT.select(groupElement("headerbytes"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int headerbytes
     * }
     */
    public static final OfInt headerbytes$layout() {
        return headerbytes$LAYOUT;
    }

    private static final long headerbytes$OFFSET = $LAYOUT.byteOffset(groupElement("headerbytes"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int headerbytes
     * }
     */
    public static final long headerbytes$offset() {
        return headerbytes$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int headerbytes
     * }
     */
    public static int headerbytes(MemorySegment struct) {
        return struct.get(headerbytes$LAYOUT, headerbytes$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int headerbytes
     * }
     */
    public static void headerbytes(MemorySegment struct, int fieldValue) {
        struct.set(headerbytes$LAYOUT, headerbytes$OFFSET, fieldValue);
    }

    private static final OfInt bodybytes$LAYOUT = (OfInt)$LAYOUT.select(groupElement("bodybytes"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int bodybytes
     * }
     */
    public static final OfInt bodybytes$layout() {
        return bodybytes$LAYOUT;
    }

    private static final long bodybytes$OFFSET = $LAYOUT.byteOffset(groupElement("bodybytes"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int bodybytes
     * }
     */
    public static final long bodybytes$offset() {
        return bodybytes$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int bodybytes
     * }
     */
    public static int bodybytes(MemorySegment struct) {
        return struct.get(bodybytes$LAYOUT, bodybytes$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int bodybytes
     * }
     */
    public static void bodybytes(MemorySegment struct, int fieldValue) {
        struct.set(bodybytes$LAYOUT, bodybytes$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

