// Generated by jextract

package io.github.kinsleykajiva.ogg;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     unsigned char *header;
 *     long header_len;
 *     unsigned char *body;
 *     long body_len;
 * }
 * }
 */
public class ogg_page {

    ogg_page() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        ogg_h.C_POINTER.withName("header"),
        ogg_h.C_LONG.withName("header_len"),
        MemoryLayout.paddingLayout(4),
        ogg_h.C_POINTER.withName("body"),
        ogg_h.C_LONG.withName("body_len"),
        MemoryLayout.paddingLayout(4)
    ).withName("$anon$42:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout header$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("header"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned char *header
     * }
     */
    public static final AddressLayout header$layout() {
        return header$LAYOUT;
    }

    private static final long header$OFFSET = $LAYOUT.byteOffset(groupElement("header"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned char *header
     * }
     */
    public static final long header$offset() {
        return header$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned char *header
     * }
     */
    public static MemorySegment header(MemorySegment struct) {
        return struct.get(header$LAYOUT, header$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned char *header
     * }
     */
    public static void header(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(header$LAYOUT, header$OFFSET, fieldValue);
    }

    private static final OfInt header_len$LAYOUT = (OfInt)$LAYOUT.select(groupElement("header_len"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * long header_len
     * }
     */
    public static final OfInt header_len$layout() {
        return header_len$LAYOUT;
    }

    private static final long header_len$OFFSET = $LAYOUT.byteOffset(groupElement("header_len"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * long header_len
     * }
     */
    public static final long header_len$offset() {
        return header_len$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * long header_len
     * }
     */
    public static int header_len(MemorySegment struct) {
        return struct.get(header_len$LAYOUT, header_len$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * long header_len
     * }
     */
    public static void header_len(MemorySegment struct, int fieldValue) {
        struct.set(header_len$LAYOUT, header_len$OFFSET, fieldValue);
    }

    private static final AddressLayout body$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("body"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned char *body
     * }
     */
    public static final AddressLayout body$layout() {
        return body$LAYOUT;
    }

    private static final long body$OFFSET = $LAYOUT.byteOffset(groupElement("body"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned char *body
     * }
     */
    public static final long body$offset() {
        return body$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned char *body
     * }
     */
    public static MemorySegment body(MemorySegment struct) {
        return struct.get(body$LAYOUT, body$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned char *body
     * }
     */
    public static void body(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(body$LAYOUT, body$OFFSET, fieldValue);
    }

    private static final OfInt body_len$LAYOUT = (OfInt)$LAYOUT.select(groupElement("body_len"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * long body_len
     * }
     */
    public static final OfInt body_len$layout() {
        return body_len$LAYOUT;
    }

    private static final long body_len$OFFSET = $LAYOUT.byteOffset(groupElement("body_len"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * long body_len
     * }
     */
    public static final long body_len$offset() {
        return body_len$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * long body_len
     * }
     */
    public static int body_len(MemorySegment struct) {
        return struct.get(body_len$LAYOUT, body_len$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * long body_len
     * }
     */
    public static void body_len(MemorySegment struct, int fieldValue) {
        struct.set(body_len$LAYOUT, body_len$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

