// Generated by jextract

package io.github.kinsleykajiva.ogg;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     long endbyte;
 *     int endbit;
 *     unsigned char *buffer;
 *     unsigned char *ptr;
 *     long storage;
 * }
 * }
 */
public class oggpack_buffer {

    oggpack_buffer() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        ogg_h.C_LONG.withName("endbyte"),
        ogg_h.C_INT.withName("endbit"),
        ogg_h.C_POINTER.withName("buffer"),
        ogg_h.C_POINTER.withName("ptr"),
        ogg_h.C_LONG.withName("storage"),
        MemoryLayout.paddingLayout(4)
    ).withName("$anon$31:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt endbyte$LAYOUT = (OfInt)$LAYOUT.select(groupElement("endbyte"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * long endbyte
     * }
     */
    public static final OfInt endbyte$layout() {
        return endbyte$LAYOUT;
    }

    private static final long endbyte$OFFSET = $LAYOUT.byteOffset(groupElement("endbyte"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * long endbyte
     * }
     */
    public static final long endbyte$offset() {
        return endbyte$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * long endbyte
     * }
     */
    public static int endbyte(MemorySegment struct) {
        return struct.get(endbyte$LAYOUT, endbyte$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * long endbyte
     * }
     */
    public static void endbyte(MemorySegment struct, int fieldValue) {
        struct.set(endbyte$LAYOUT, endbyte$OFFSET, fieldValue);
    }

    private static final OfInt endbit$LAYOUT = (OfInt)$LAYOUT.select(groupElement("endbit"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int endbit
     * }
     */
    public static final OfInt endbit$layout() {
        return endbit$LAYOUT;
    }

    private static final long endbit$OFFSET = $LAYOUT.byteOffset(groupElement("endbit"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int endbit
     * }
     */
    public static final long endbit$offset() {
        return endbit$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int endbit
     * }
     */
    public static int endbit(MemorySegment struct) {
        return struct.get(endbit$LAYOUT, endbit$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int endbit
     * }
     */
    public static void endbit(MemorySegment struct, int fieldValue) {
        struct.set(endbit$LAYOUT, endbit$OFFSET, fieldValue);
    }

    private static final AddressLayout buffer$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("buffer"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned char *buffer
     * }
     */
    public static final AddressLayout buffer$layout() {
        return buffer$LAYOUT;
    }

    private static final long buffer$OFFSET = $LAYOUT.byteOffset(groupElement("buffer"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned char *buffer
     * }
     */
    public static final long buffer$offset() {
        return buffer$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned char *buffer
     * }
     */
    public static MemorySegment buffer(MemorySegment struct) {
        return struct.get(buffer$LAYOUT, buffer$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned char *buffer
     * }
     */
    public static void buffer(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(buffer$LAYOUT, buffer$OFFSET, fieldValue);
    }

    private static final AddressLayout ptr$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("ptr"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned char *ptr
     * }
     */
    public static final AddressLayout ptr$layout() {
        return ptr$LAYOUT;
    }

    private static final long ptr$OFFSET = $LAYOUT.byteOffset(groupElement("ptr"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned char *ptr
     * }
     */
    public static final long ptr$offset() {
        return ptr$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned char *ptr
     * }
     */
    public static MemorySegment ptr(MemorySegment struct) {
        return struct.get(ptr$LAYOUT, ptr$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned char *ptr
     * }
     */
    public static void ptr(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(ptr$LAYOUT, ptr$OFFSET, fieldValue);
    }

    private static final OfInt storage$LAYOUT = (OfInt)$LAYOUT.select(groupElement("storage"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * long storage
     * }
     */
    public static final OfInt storage$layout() {
        return storage$LAYOUT;
    }

    private static final long storage$OFFSET = $LAYOUT.byteOffset(groupElement("storage"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * long storage
     * }
     */
    public static final long storage$offset() {
        return storage$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * long storage
     * }
     */
    public static int storage(MemorySegment struct) {
        return struct.get(storage$LAYOUT, storage$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * long storage
     * }
     */
    public static void storage(MemorySegment struct, int fieldValue) {
        struct.set(storage$LAYOUT, storage$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

